Bf-025 Add Seen resource
BTS-Interns/bimflix pull request #17
Opened 2016-12-02 18:50 UTC by shockolegario

2016-12-02 18:59 UTC, shockolegario commented
for this task I use the ngResource

2016-12-02 22:40 UTC, CarlosPadilla approved these changes

2016-12-02 22:46 UTC, devRodSoft requested changes

2016-12-02 22:46 UTC, Rjavy commented on blimflix/client/app/providers/seen.factory.js
> +      'remove': { method:'DELETE'}
Just a suggestion: When you have variable/object assign value is a good practice code like this example, look the right values are align with the same spaces after the ":", this way is more readily :) 

'query':    { method: 'GET', isArray: true},
'save':      { method: 'POST' },
'remove': { method:'DELETE'}

2016-12-03 23:17 UTC, shockolegario commented
Ready, I corrected the observation

2016-12-04 20:12 UTC, shockolegario reviewed
ready

2016-12-04 20:12 UTC, shockolegario commented on blimflix/client/app/providers/seen.factory.js
> +      'remove': { method:'DELETE'}
ready

2016-12-04 22:19 UTC, lordpixel approved these changes

2016-12-06 23:36 UTC, devRodSoft approved these changes

2016-12-06 23:41 UTC, devRodSoft approved these changes

2016-12-07 16:32 UTC, merged