Directive movie details bf-024 ready for testing
BTS-Interns/bimflix pull request #18
Opened 2016-12-02 22:04 UTC by Axl-Nolasco

The file movie-details.js has some code commented for future use

2016-12-02 22:38 UTC, CarlosPadilla approved these changes

2016-12-02 22:38 UTC, CarlosPadilla commented on blimflix/client/app/directives/movie-details/movie-details.scss
> +.rank {
this class has no contents. if it isn't required then remove it

2016-12-04 22:16 UTC, lordpixel commented
Hi @Axl-Nolasco, how can we display the directive?

2016-12-04 22:19 UTC, Axl-Nolasco commented
Hi Manu. In the file .js there are some lines of code of a button with specific classes that display the modal. If you put this code in the all movies html you can visualize it.



On Sun, Dec 4, 2016 at 4:16 PM -0600, "Manuel Ramirez" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @Axl-Nolasco<https://github.com/Axl-Nolasco>, how can we display the directive?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/BTS-Interns/blimflix/pull/18#issuecomment-264735958>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AUJ25OQ5gz3bLl7-JL2QaQQRqnng3SXpks5rEzvQgaJpZM4LDCbr>.

2016-12-06 23:41 UTC, devRodSoft approved these changes

2016-12-06 23:41 UTC, devRodSoft commented on blimflix/client/app/directives/movie-details/movie-details.scss
> +.staff h6{
Plase add space after h6

2016-12-06 23:41 UTC, devRodSoft commented on blimflix/client/app/directives/movie-details/movie-details.scss
> +.staff p{
Add space after p

2016-12-07 01:30 UTC, CarlosPadilla requested changes

2016-12-07 01:30 UTC, CarlosPadilla commented on blimflix/client/app/directives/movie-details/movie-details.scss
> +.info div {
please nest the repeated  data

2016-12-07 17:17 UTC, CarlosPadilla requested changes

2016-12-07 17:17 UTC, CarlosPadilla commented on blimflix/client/app/directives/movie-details/movie-details.scss
> +.info div {
this changes can affect all over the application. please make it nested
now you are setting global style changes for elements

2016-12-07 17:32 UTC, CarlosPadilla approved these changes

2016-12-07 17:32 UTC, merged