Favorites factory BF-026
BTS-Interns/bimflix pull request #20
Opened 2016-12-05 20:32 UTC by Migueld1324

2016-12-06 23:39 UTC, devRodSoft approved these changes

2016-12-07 00:46 UTC, CarlosPadilla requested changes

2016-12-07 00:46 UTC, CarlosPadilla commented on blimflix/client/app/providers/favorites.factory.js
> +        'get'   : { method: 'GET', isArray: true, },
could be better use the same convention for all the resourses
the standard convention is
```
query : GET an array of elements
get : GET just one of these elements
save: POST create a new element
delete: DELETE one of these elements
remove: same as delete
update: PUT update one of these elements
```

2016-12-07 00:46 UTC, Migueld1324 commented on blimflix/client/app/providers/favorites.factory.js
> +        'get'   : { method: 'GET', isArray: true, },
Ok, working on that!

2016-12-07 00:47 UTC, Migueld1324 commented on blimflix/client/app/providers/favorites.factory.js
> +        'get'   : { method: 'GET', isArray: true, },
so, it has to be query, save and remove or delete in this case, right?

2016-12-07 01:27 UTC, CarlosPadilla approved these changes
That's right

2016-12-07 16:33 UTC, merged